---
branches:
  only:
    - "master"
language: go
go:
  - 1.x
  - tip
env:
  global: 
    - GO111MODULE=on
cache:
  directories:
    - "$HOME/gopath/pkg/mod"
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - make tools
script:
  - hack/coverage.sh --coveralls
  - make
notifications:
  email: false
