---
language: go
go:
  - 1.9.1
install:
  - make tools
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - make
  - make vendor-status
notifications:
  email: false
