
[[dependencies]]
  name = "github.com/Sirupsen/logrus"
  version = "^0.11.5"

[[dependencies]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.8.17"

[[dependencies]]
  branch = "master"
  name = "github.com/golang/protobuf"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/viper"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/net"

[[dependencies]]
  name = "google.golang.org/grpc"
  version = "^1.2.1"
